=== mmusich/usercode/ZbbAnalysis/AnalysisStep/macros/sample.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT SampleList (Sample)+ >
<!ELEMENT Sample (InputRootFile,Label,Color,Lumi?,XSection) >

<!ATTLIST Sample ID CDATA #REQUIRED >
<!ATTLIST Sample IsMC (true|false) "false" >

<!ELEMENT InputRootFile (#PCDATA) >
<!ELEMENT Label         (#PCDATA) >
<!ELEMENT Color         (#PCDATA) >
<!ELEMENT Lumi          (#PCDATA) > <!-- lumi in 1/pb -->
<!ELEMENT XSection      (#PCDATA) > <!-- x-sec in pb -->

=== mmusich/usercode/ZbbAnalysis/AnalysisStep/macros/sample.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE SampleList SYSTEM "sample.dtd">

<SampleList>
<!--This is the sample list -->
  <Sample ID="1" IsMC ="false">
	  <InputRootFile>analyzePAT_DATA2011.root</InputRootFile>
	  <Label>CMS DATA 2011</Label>
	  <Color>1</Color>
	  <Lumi>2220 </Lumi>
	  <XSection>0</XSection>
  </Sample>
  <Sample ID="2" IsMC="true">
	  <InputRootFile>analyzePAT_MC_TTJets_All.root</InputRootFile>
	  <Label>MC t#bar{t}</Label>
	  <Color>393</Color>
	  <Lumi>2220</Lumi>
	  <XSection>165</XSection>
  </Sample>
  <Sample ID="3" IsMC="true">
	  <InputRootFile>analyzePAT_MC_ZtautauJets_All.root</InputRootFile>
	  <Label>MC Z(#tau#tau)</Label>
	  <Color>19</Color>
	  <Lumi>2220</Lumi>
	  <XSection>3048</XSection>
  </Sample>
  <Sample ID="4" IsMC="true">
          <InputRootFile>analyzePAT_MC_ZZ_All.root</InputRootFile>
	  <Label>MC ZZ</Label>
	  <Color>6</Color>
	  <Lumi>2220</Lumi>
	  <XSection>6.4</XSection>
  </Sample>
  <Sample ID="5" IsMC="true">
	  <InputRootFile>analyzePAT_MC_ZW_TNP.root</InputRootFile>
          <Label>MC WZ</Label>
          <Color>9</Color>
	  <Lumi>2220</Lumi>
	  <XSection>19.79</XSection>
  </Sample>
  <Sample ID="6" IsMC="true">
	  <InputRootFile>analyzePAT_MC_Zb5fToLL_All.root</InputRootFile>
	  <Label>MC Z+b</Label>
	  <Color>628</Color>
	  <Lumi>2220</Lumi>
	  <XSection>3048</XSection>
  </Sample>
  <Sample ID="7" IsMC="true">
	  <InputRootFile>analyzePAT_MC_ZcToLL_All.root</InputRootFile>
	  <Label>MC Z+c</Label>
	  <Color>409</Color>
	  <Lumi>2220</Lumi>
	  <XSection>3048</XSection>
  </Sample>
  <Sample ID="8" IsMC="true">
	  <InputRootFile>analyzePAT_MC_ZlJets_All.root</InputRootFile>
	  <Label>MC Z+l</Label>
	  <Color>856</Color>
	  <Lumi>2220</Lumi>
	  <XSection>3048</XSection>
  </Sample>
</SampleList>
